a= "when i told1 you"

print(a.capitalize())
print(a.title())
print(a.isalpha())
print(a.isnumeric())
print(a.isalnum())
print(a.lower())
print(a.upper())
print(a.isupper())
print(a.islower())
print(a.isascii())
print(a.isdigit())
print(a.find("to"))
print(a.replace("1", "0"))
print(a.swapcase())
print(a.strip())
print(a.encode())
print(a.casefold())
# print(a.is)
# print(a.sorted())
print(''.join(sorted("sunny")))